### ISSUE TITLE
PDF support?

### ISSUE THREAD

**Issue by chmac** [Pixboost/transformimgs#28]
Does this application support PDFs as a possible upload media?

I saw that PNGs / JPEGs can be resized, so maybe PDFs are not supported...

Apologies if this was answered online somewhere, I tried to find the answer in the issues and google, but failed...

**Comment by dooman87** [comment]
Hi Callum,

Thanks a lot for the question. You are 100% right when saying you couldn't find any info on PDF cause it's not there.

PDFs are currently not supported, except `/asis` endpoint which will just return original PDF file. This could be used in case you'd want to put something behind CDN.

Sorry, I think I'm not 100% understood what you mean by `support PDFs as a possible upload media`? The application doesn't support upload and act as a proxy. For instance,

http://localhost:8080/img/http://images.com/image.jpeg/optimise

will load an image from `http://images.com/image.jpeg` and optimizes it.

If we would add PDF support, then would you expect resize endpoint return raster image, e.g. JPEG/WebP/AVIF?

**Comment by chmac** [comment]
@dooman87 Sorry for the very slow reply. I was thinking about generating thumbnails from PDFs. I'd guess that the thumbnail would be a PNG or so. But the project this topic was for has now since been closed, so my use case is no longer active.

I'll close this now as it seems fair that you've answered the question, PDFs are not currently supported.

Thanks for sharing and maintaining open source software.
